matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - CXXFLAGS="-std=c++11"
         - LD_LIBRARY_PATH=./lib

language: rust
rust:
  - stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
