version: 1.0.{build}
branches:
  only:
  - master
clone_folder: c:\clone
environment:
  matrix:
  - RUST_URL: https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.msi
    RUST_INSTALLER: rust-nightly-x86_64-pc-windows-msvc.msi
install:
- cmd: >-
    appveyor DownloadFile %RUST_URL%
    
    msiexec /i %RUST_INSTALLER% INSTALLDIR="c:\rust" /qn
    
    SET PATH=c:\rust\bin;%PATH%

build_script:
- cmd: >-
    SET RUST_BACKTRACE=1
    
    cargo build --release
    
    cargo test --release
    
after_build:
- cmd: >-
   copy target\release\3dtile.exe bin\
   

artifacts:
  - path: bin
    name: 3dtiles
    
    
    
